apps_global/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('b_apps.urls')),
    path('quiz/', include('d_apps_quiz.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('kinopoisk/', include('c_apps_kinopoisk.urls')),

    path('',include('e_apps_shop.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

b_apps/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.test,name='test_view'),
    path('category_list/',views.test,name='category_url'),
    path('news_object/',views.test,name='news_objects_url'),

]

c_apps_kinopoisk/urls.py
from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path('tm/',views.Info.as_view(),name='tigr'),
    path('<slug:slug>/ts/',views.Test.as_view(),name='test_class'),#testviewclass
    path('',views.MovieView.as_view(),name='test_view'),#testViewDef
    path('<slug:slug>/',views.MovieDetailView.as_view(),name='movie_detail'),
    path('review/<int:pk>/',views.AddReview.as_view(),name='add_review'),
    path('<int:id>/',views.MovieViewfilter.as_view(),name='movie_view_filter'),
]

c_apps_kinopoisk/models.py
from datetime import date
from django.db import models
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor.fields import RichTextField
from django.utils.text import slugify
class Category(models.Model):
    name = models.CharField('категория' ,max_length=150)
    description = RichTextUploadingField('описание')
    url = models.SlugField(max_length=160,unique=True)
    def __str__(self):
        return self.name
    def save(self,*args,**kwargs):
        if not self.url:
            self.url=slugify(self.name)
        return super().save(*args,**kwargs)
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural ='Категории'
class Actor(models.Model):
    name = models.CharField('имя',max_length=100)
    surname = models.CharField('фамилия',max_length=100)
    age = models.PositiveSmallIntegerField('возраст',default=0)
    description = RichTextUploadingField('описание')
    image = models.ImageField('изображение актера', upload_to='media/c_apps_kinopoisk/actors/%Y/%m/%d/')
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'Актер'
        verbose_name_plural ='Актеры'
class Genre(models.Model):
    name = models.CharField('жанр', max_length=150)
    description = RichTextUploadingField('описание')
    url = models.SlugField(max_length=160, unique=True)
    class Meta:
        verbose_name = 'Жанры'
        verbose_name_plural ='Жанры'
    def __str__(self):
        return self.name
    def save(self,*args,**kwargs):
        if not self.url:
            self.url=slugify(self.name)
        return self.url
class Movie(models.Model):
    title = models.CharField('название',max_length=150)
    tagline = models.CharField('слоган',max_length=150,default='')
    description = RichTextUploadingField('описание')
    poster = models.ImageField('poster', upload_to='media/c_apps_kinopoisk/posters/%Y/%m/%d/')
    year = models.PositiveSmallIntegerField('дата выхода',default=2022)
    country = models.CharField('страна',max_length=30)
    directors = models.ManyToManyField(Actor,verbose_name='режисер',related_name='film_director')
    actors = models.ManyToManyField(Actor,verbose_name='актер',related_name='film_actor')
    genres = models.ManyToManyField(Genre,verbose_name='жанр')
    world_premiere = models.DateField('премьера в мире',default=date.today)
    budget = models.PositiveIntegerField('бюджет',default=0)
    fees_in_usa = models.PositiveIntegerField('сборы в США',default=0)
    fees_in_world = models.PositiveIntegerField('сборы в мире',default=0)
    category = models.ForeignKey(Category,on_delete=models.SET_NULL,null=True)
    url = models.SlugField(max_length=160,unique=True)
    draft = models.BooleanField('черновик',default=False)
    def __str__(self):
        return self.title
    def save(self,*args,**kwargs):
        if not self.url:
            self.url=slugify(self.title)
        return super().save(*args,**kwargs)
    def get_absolute_url(self):
        return reverse('movie_detail',kwargs={'slug':self.url })
    class Meta:
        verbose_name = 'Фильм'
        verbose_name_plural ='Фильмы'
        ordering = ['-country']
class MovieShots(models.Model):
    title = models.CharField('заголовки',max_length=150)
    description = RichTextUploadingField('описание')
    image = models.ImageField('изображение', upload_to='media/c_apps_kinopoisk/posters/%Y/%m/%d/')
    movie = models.ForeignKey(Movie,verbose_name='фильм',on_delete=models.CASCADE)
    def __str__(self):
        return self.movie.title
    class Meta:
        verbose_name = 'Фрагмент'
        verbose_name_plural ='Фрагменты'
class RattingStar(models.Model):
    value = models.PositiveSmallIntegerField('значение',default=0)
    class Meta:
        verbose_name = 'Рейтинг звезд'
        verbose_name_plural ='Рейтинг звезд'
class Rating(models.Model):
    ip = models.CharField('ip адресс',max_length=15)
    star = models.ForeignKey(RattingStar,on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie,on_delete=models.CASCADE)
    class Meta:
        verbose_name = 'Рейтинг'
        verbose_name_plural ='Рейтинг'
class Reviews(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=150)
    text = RichTextUploadingField()
    parent = models.ForeignKey('self',on_delete=models.SET_NULL,null=True, blank=True)
    movie = models.ForeignKey(Movie,on_delete=models.CASCADE)
    def __str__(self):
        return self.movie.title
    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural ='Отзывы'

c_apps_kinopoisk/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView,DetailView
from django.views.generic.base import View

from .form import ReviewForm
from .models import Movie,Actor
class MovieView(ListView):
    model = Movie
    queryset = Movie.objects.filter(draft=False)
    template_name = 'c_apps_kinopoisk/base_temp/movie_list.html'
    context_object_name = 'movie_list'
class MovieDetailView(DetailView):
    model = Movie
    slug_field = 'url' #
    template_name = 'c_apps_kinopoisk/base_temp/movie_detail.html'
    context_object_name = 'movie_list'
class MovieViewfilter(View):
    def get(self,request):
        movies = Movie.objects.filter(genres=self.kwargs['id'])
        return render(request,'c_apps_kinopoisk/base_temp/movie_list.html',context={'movie_list':movies})
class AddReview(View):
    """отзывы"""
    def post(self,request,pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if form.is_valid():
            form=form.save(commit=False)
            form.movie_id = pk
            form.movie=movie
            form.save()
        return redirect(movie.get_absolute_url())
def tests(request):
    return render(request,template_name='c_apps_kinopoisk/test.html')
class Test(View):
    def get(self,request, *args,**kwargs):
        print(request.user.last_login)
        obj=Movie.objects.filter(country=self.kwargs['slug'])
        return render(request,template_name='test.html',context={'object_list':obj})
class Info(ListView):
    model = Movie
    template_name = 'Info.html'
    context_object_name = 'object_lisr'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['dim'] = [1,2,3,4,5,6]
        return context

d_apps_quiz/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from .models import Quiz

class ViewQuiz(ListView):
    model = Quiz
    template_name = 'd_apps_quiz/shabons/quiz.html'
    context_object_name = 'object_list'


class DetailQuiz(DetailView):
    model = Quiz
    slug_field = 'url'
    template_name = 'd_apps_quiz/shabons/detail_quiz.html'
    context_object_name = 'object'

    def get_context_data(self, **kwargs):
        self.kwargs['tigrito']='димасия'
        print(self.kwargs.items())
        return super().get_context_data(**kwargs)


class ViewsQuiz(ListView):
    model = Quiz
    template_name = 'd_apps_quiz/shabons/quiz2.html'

c_apps_kinopoisk/templates/c_apps_kinopoisk/base_temp/movie_detail.html
{% extends 'c_apps_kinopoisk/base.html' %}
{% load static %}
    {% block title %}
Clack Website Template
    {% endblock %}


    {% block body %}
    <div id="page" class="page"><!-- mian-content -->
        <div class="main-banner bg bg1" id="home" style="background-color: rgba(0, 0, 0, 0); margin-top: 0px; background-image: url(&quot;bundles/single-post-pic.jpg&quot;);">
            <!-- header -->
            <header class="header">
                <div class="container-fluid px-lg-5">
                    <!-- nav -->

                    <!-- //nav -->
                </div>
            </header>
                <div class="row">
                        <div class="container d-flex align-items-center justify-content-center">
                            <div class="product-shoe-info editContent text-center mt-lg-4">
                            <div class="men-thumb-item">
                                <img src="{{ movie_list.poster.url }}" alt="">
                            </div>
                            <div class="item-info-product">
                                <a href="{{ movie_list.id }}" class="editContent">{{ movie_list.title }} </a>
                            </div>
                                {{ movie_list.poster.url }}

                            </div>
                            <div>
                                {{ movie_list.description | safe }}

                                {% lorem 4 p random %}
                            </div>
                        </div>
                </div>
        </div>

        {% for image in movie_list.movieshots_set.all %}
            <img src="{{ image.image.url }}" class="img-movie-shots" alt="{{ image.description }}">
        {% endfor %}
        <form action="{% url 'add_review' movie_list.id %}" method="post" class="mt-1">
            {% csrf_token %}
            <div class="form-group editContent" style="...">
                <label for="contactcomment" class="editContent" style="...">Ваш комментарий</label>
                <textarea class="form-control border" rows="2" name="text" id="contactcomment" required=""></textarea>
            </div>

        <div class="d-sm-flex">
            <div class="col-sm-6 form-group p-0 editContent" style="...">
                <label for="contactusername" class="editContent" style="...">name</label>
                    <input type="text" class="form-control border" name="name" id="contactusername" required="">
            </div>

            <div class="col-sm-6 form-group ml-sm-3 editContent" style="...">
                <label for="contactemail" class="editContent" style="...">email</label>
                    <input type="text" class="form-control border"  name='email' id="contactemail" required="">
            </div>
            </div>
            <button type="submit" class="mt-3 btn btn-success btn-block py-3">run
            </button>

            </form>

        <div class="container-md">
            <h2 class="my-4 editContent">Отзывы:</h2>

            {% for reviews in movie_list.reviews_set.all %}

            <h5 class="mt-0 editContent">
                {{ reviews.name }}
            </h5>
        <p class="mt-2 editContent">{{ reviews.text }}</p>
        <div class="media mt-5 editContent">
        </div>
            {% empty %}
                    <p class="mt-2 editContent">оставьте отзыв первым</p>

            {% endfor %}
        </div>
    </div>

    {% endblock %}