apps_global/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('b_apps.urls')),
    path('quiz/', include('d_apps_quiz.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('kinopoisk/', include('c_apps_kinopoisk.urls')),

    path('',include('e_apps_shop.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

b_apps/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.test,name='test_view'),
    path('category_list/',views.test,name='category_url'),
    path('news_object/',views.test,name='news_objects_url'),

]

e_apps_shop/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.HomePage.as_view()),
    path('category/',views.ViewCategory.as_view()),
    path('category/<int:pk>/',views.ViewItem.as_view(),name='items'),
]

e_apps_shop/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=255,unique=True)
    image = models.ImageField(verbose_name='Изображение',upload_to='uploads/shop/category/%Y/%m/%d/',null=True)
    url = models.SlugField(verbose_name='ссылка',max_length=300)
    description = RichTextUploadingField(verbose_name='описание')
    def __str__(self):
        return self.name


class Items(models.Model):
    name = models.CharField(max_length=255)
    url = models.SlugField(max_length=300)
    image = models.ImageField(upload_to='uploads/shop/items/%Y/%m/%d/',null=True)
    description = RichTextUploadingField(verbose_name='описание')
    category = models.ForeignKey(Category,on_delete=models.SET_NULL,null=True)
    def get_absolute_url(self):
        return reverse('items',kwargs=self.kwargs['pk'])
    def save(self,*args,**kwargs):
        if not(self.url):
            self.url = slugify(self.name)
        return super().save(*args,**kwargs)

e_apps_shop/views.py
from django.shortcuts import render
from django.views import View,generic
from .models import Category,Items
from c_apps_kinopoisk.models import Movie
class HomePage(View):
    def get(self,request):
        print(type(request.user))
        if str(request.user) in ['admin','dimas','olesik']:
            context = {'one': [1,2,3,4,5,6,7,8,9,20],'two':request.user,'movie_list':Movie.objects.all()}
        elif str(request.user) == 'AnonymousUser':
            context = {'one': [22, 23, 24, 25, 27, 26, 28], 'two': 'братик? ты не зареган?" не надо так!','movie_list':Movie.objects.all()}
        else:
            context = {'one':Items.objects.all(),'two':request.user,'movie_list':Movie.objects.all()}
        return render(request,template_name='e_apps_shop/shablons/home.html',context=context)

class ViewCategory(generic.ListView):
    template_name = 'e_apps_shop/shablons/category_list.html'
    model = Category
    context_object_name = 'object_list'
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['count_element'] = 5
        return context

class ViewItem(generic.DetailView):
    template_name = 'e_apps_shop/shablons/viewitem_detail.html'
    model = Items
    context_object_name = 'object'

e_apps_shop/templates/e_apps_shop/shablons/category_list.html
{% extends 'e_apps_shop/base.html' %}
{% block title %}виджет категорий {% endblock title %}

{% block body %}

{% for object in object_list %}
<div class="container">
<div class="row row-cols-4">

    {% for i in object.items_set.all %}
    <div class="col">
        <a href="{{ i.pk }}">{{ i.name }}</a>
        <div>
        <img src="{{ i.image.url }}" alt="" width="200" height="140">
        </div>

        <h3>{{ i.pk }} of {{ count_element }}</h3>
    </div>


    {% endfor %}
</div>
    </div>
    {% endfor %}

{% endblock body %}

e_apps_shop/templates/e_apps_shop/shablons/category_list2.html
{% extends 'e_apps_shop/base.html' %}
{% block title %}виджет категорий {% endblock title %}



  два ептыть

{% endblock body %}

e_apps_shop/templates/e_apps_shop/shablons/viewitem_detail.html
{% extends 'e_apps_shop/base.html' %}
{% block title %}виджет категорий {% endblock title %}

{% block body %}
<h2>{{ object.name }}</h2>
<p>

<div class="container">
<div class="row row-cols-3">
<div class="col">
<img src="{{ object.image.url }}" alt=""></p>

    <div class="col">
        характеристики

    </div>
    </div>

    {{ object.description|safe }}
    <div class="col ">

    {% for obj in object.category_set.all %}

        {{ obj }}

    {% endfor %}
    </div>
    </div>
    </div>
{% endblock body %}